### ISSUE TITLE
제안) Haekyung-헤더 html, css

### ISSUE THREAD

**Issue by hae9** [fastcampus-team4/Aesop#3]
## description

헤더 구조 만들기

## task

- [x] html, css 연결
- [x] html 구조 작성
- [x] css 스타일 작성
